name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # daily:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  examples:
    runs-on: ubuntu-latest
    env:
      DUFFEL_ACCESS_TOKEN: ${{ secrets.DUFFEL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan example
      - name: Upload built artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: |
            build/libs/
            build/reports/
